//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.16 at 11:52:48 AM EDT 
//


package com.taksila.veda.model.api.usermgmt.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.taksila.veda.model.api.base.v1_0.BaseResponse;
import com.taksila.veda.model.db.usermgmt.v1_0.User;
import com.taksila.veda.model.db.usermgmt.v1_0.UserImageInfo;


/**
 * 
 * 				This represents the api structure of the GetConfigurationResponse response 				
 * 			
 * 
 * <p>Java class for GetUserResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetUserResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/api/base/v1_0}BaseResponse">
 *       &lt;sequence>
 *         &lt;element name="user" type="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}User"/>
 *         &lt;element name="profileImageInfo" type="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}UserImageInfo"/>
 *         &lt;element name="socialImagesList" type="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}UserImageInfo" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetUserResponse", propOrder = {
    "user",
    "profileImageInfo",
    "socialImagesList"
})
public class GetUserResponse
    extends BaseResponse
{

    @XmlElement(required = true)
    protected User user;
    @XmlElement(required = true)
    protected UserImageInfo profileImageInfo;
    @XmlElement(required = true)
    protected List<UserImageInfo> socialImagesList;

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the profileImageInfo property.
     * 
     * @return
     *     possible object is
     *     {@link UserImageInfo }
     *     
     */
    public UserImageInfo getProfileImageInfo() {
        return profileImageInfo;
    }

    /**
     * Sets the value of the profileImageInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserImageInfo }
     *     
     */
    public void setProfileImageInfo(UserImageInfo value) {
        this.profileImageInfo = value;
    }

    /**
     * Gets the value of the socialImagesList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the socialImagesList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSocialImagesList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserImageInfo }
     * 
     * 
     */
    public List<UserImageInfo> getSocialImagesList() {
        if (socialImagesList == null) {
            socialImagesList = new ArrayList<UserImageInfo>();
        }
        return this.socialImagesList;
    }

}
