//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.09 at 08:28:21 AM EDT 
//


package com.taksila.veda.model.db.config.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.taksila.veda.model.db.base.v1_0.BaseTable;


/**
 * 
 * 				Saves the sysadmin and tenant admin configuration entry							
 * 			
 * 
 * <p>Java class for ConfigGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigGroup">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/db/base/v1_0}BaseTable">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/config/v1_0}configGroupName"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/config/v1_0}footerNote"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/config/v1_0}headerNote"/>
 *         &lt;element name="configs" type="{http://www.taksila.com/veda/model/db/config/v1_0}Config" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigGroup", propOrder = {
    "configGroupName",
    "footerNote",
    "headerNote",
    "configs"
})
public class ConfigGroup
    extends BaseTable
{

    @XmlElement(required = true)
    protected String configGroupName;
    @XmlElement(required = true)
    protected String footerNote;
    @XmlElement(required = true)
    protected String headerNote;
    @XmlElement(required = true)
    protected List<Config> configs;

    /**
     * Gets the value of the configGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigGroupName() {
        return configGroupName;
    }

    /**
     * Sets the value of the configGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigGroupName(String value) {
        this.configGroupName = value;
    }

    /**
     * Gets the value of the footerNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFooterNote() {
        return footerNote;
    }

    /**
     * Sets the value of the footerNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFooterNote(String value) {
        this.footerNote = value;
    }

    /**
     * Gets the value of the headerNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderNote() {
        return headerNote;
    }

    /**
     * Sets the value of the headerNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderNote(String value) {
        this.headerNote = value;
    }

    /**
     * Gets the value of the configs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the configs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfigs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Config }
     * 
     * 
     */
    public List<Config> getConfigs() {
        if (configs == null) {
            configs = new ArrayList<Config>();
        }
        return this.configs;
    }

}
