//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.10 at 06:58:02 PM EDT 
//


package com.taksila.veda.model.db.config.v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.taksila.veda.model.db.config.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AllowBlankValue_QNAME = new QName("http://www.taksila.com/veda/model/db/config/v1_0", "allowBlankValue");
    private final static QName _SectionName_QNAME = new QName("http://www.taksila.com/veda/model/db/config/v1_0", "sectionName");
    private final static QName _ConfigGroupName_QNAME = new QName("http://www.taksila.com/veda/model/db/config/v1_0", "configGroupName");
    private final static QName _ConfigId_QNAME = new QName("http://www.taksila.com/veda/model/db/config/v1_0", "configId");
    private final static QName _ViewXtype_QNAME = new QName("http://www.taksila.com/veda/model/db/config/v1_0", "viewXtype");
    private final static QName _SectionId_QNAME = new QName("http://www.taksila.com/veda/model/db/config/v1_0", "sectionId");
    private final static QName _ConfigValue_QNAME = new QName("http://www.taksila.com/veda/model/db/config/v1_0", "configValue");
    private final static QName _ConfigType_QNAME = new QName("http://www.taksila.com/veda/model/db/config/v1_0", "configType");
    private final static QName _ConfigGroupId_QNAME = new QName("http://www.taksila.com/veda/model/db/config/v1_0", "configGroupId");
    private final static QName _FooterNote_QNAME = new QName("http://www.taksila.com/veda/model/db/config/v1_0", "footerNote");
    private final static QName _HeaderNote_QNAME = new QName("http://www.taksila.com/veda/model/db/config/v1_0", "headerNote");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.taksila.veda.model.db.config.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link ConfigSection }
     * 
     */
    public ConfigSection createConfigSection() {
        return new ConfigSection();
    }

    /**
     * Create an instance of {@link ConfigGroup }
     * 
     */
    public ConfigGroup createConfigGroup() {
        return new ConfigGroup();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/config/v1_0", name = "allowBlankValue")
    public JAXBElement<Boolean> createAllowBlankValue(Boolean value) {
        return new JAXBElement<Boolean>(_AllowBlankValue_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/config/v1_0", name = "sectionName")
    public JAXBElement<String> createSectionName(String value) {
        return new JAXBElement<String>(_SectionName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/config/v1_0", name = "configGroupName")
    public JAXBElement<String> createConfigGroupName(String value) {
        return new JAXBElement<String>(_ConfigGroupName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/config/v1_0", name = "configId")
    public JAXBElement<String> createConfigId(String value) {
        return new JAXBElement<String>(_ConfigId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/config/v1_0", name = "viewXtype")
    public JAXBElement<String> createViewXtype(String value) {
        return new JAXBElement<String>(_ViewXtype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/config/v1_0", name = "sectionId")
    public JAXBElement<String> createSectionId(String value) {
        return new JAXBElement<String>(_SectionId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/config/v1_0", name = "configValue")
    public JAXBElement<String> createConfigValue(String value) {
        return new JAXBElement<String>(_ConfigValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/config/v1_0", name = "configType")
    public JAXBElement<String> createConfigType(String value) {
        return new JAXBElement<String>(_ConfigType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/config/v1_0", name = "configGroupId")
    public JAXBElement<String> createConfigGroupId(String value) {
        return new JAXBElement<String>(_ConfigGroupId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/config/v1_0", name = "footerNote")
    public JAXBElement<String> createFooterNote(String value) {
        return new JAXBElement<String>(_FooterNote_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/config/v1_0", name = "headerNote")
    public JAXBElement<String> createHeaderNote(String value) {
        return new JAXBElement<String>(_HeaderNote_QNAME, String.class, null, value);
    }

}
