//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 06:19:21 AM EDT 
//


package com.taksila.veda.model.db.security.v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.taksila.veda.model.db.security.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LastLoginOn_QNAME = new QName("http://www.taksila.com/veda/model/db/security/v1_0", "lastLoginOn");
    private final static QName _SessionToken_QNAME = new QName("http://www.taksila.com/veda/model/db/security/v1_0", "sessionToken");
    private final static QName _UserId_QNAME = new QName("http://www.taksila.com/veda/model/db/security/v1_0", "userId");
    private final static QName _Client_QNAME = new QName("http://www.taksila.com/veda/model/db/security/v1_0", "client");
    private final static QName _ExpiresOn_QNAME = new QName("http://www.taksila.com/veda/model/db/security/v1_0", "expiresOn");
    private final static QName _IpAddr_QNAME = new QName("http://www.taksila.com/veda/model/db/security/v1_0", "ipAddr");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.taksila.veda.model.db.security.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserSession }
     * 
     */
    public UserSession createUserSession() {
        return new UserSession();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/security/v1_0", name = "lastLoginOn")
    public JAXBElement<XMLGregorianCalendar> createLastLoginOn(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_LastLoginOn_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/security/v1_0", name = "sessionToken")
    public JAXBElement<String> createSessionToken(String value) {
        return new JAXBElement<String>(_SessionToken_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/security/v1_0", name = "userId")
    public JAXBElement<String> createUserId(String value) {
        return new JAXBElement<String>(_UserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/security/v1_0", name = "client")
    public JAXBElement<String> createClient(String value) {
        return new JAXBElement<String>(_Client_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/security/v1_0", name = "expiresOn")
    public JAXBElement<XMLGregorianCalendar> createExpiresOn(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ExpiresOn_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/security/v1_0", name = "ipAddr")
    public JAXBElement<String> createIpAddr(String value) {
        return new JAXBElement<String>(_IpAddr_QNAME, String.class, null, value);
    }

}
