//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 03:53:26 PM EST 
//


package com.taksila.veda.model.db.security.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				This represents the structure of the password verification token table				
 * 			
 * 
 * <p>Java class for UserTable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserTable">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}id"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}userId"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}username"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}firstName"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}lastName"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}profileImage"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}emailId"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}isAdmin"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}createdDate"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}updatedBy"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}updatedDate"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}userAgreementAccepted"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}privacyPolicyAgreementAccepted"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}onBoardingComplete"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}mobilePhone"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}officePhone"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}password"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/security/v1_0}passcode"/>
 *         &lt;element name="roles" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserTable", propOrder = {
    "id",
    "userId",
    "username",
    "firstName",
    "lastName",
    "profileImage",
    "emailId",
    "isAdmin",
    "createdDate",
    "updatedBy",
    "updatedDate",
    "userAgreementAccepted",
    "privacyPolicyAgreementAccepted",
    "onBoardingComplete",
    "mobilePhone",
    "officePhone",
    "password",
    "passcode",
    "roles"
})
public class UserTable {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String userId;
    @XmlElement(required = true)
    protected String username;
    @XmlElement(required = true)
    protected String firstName;
    @XmlElement(required = true)
    protected String lastName;
    @XmlElement(required = true)
    protected byte[] profileImage;
    @XmlElement(required = true)
    protected String emailId;
    protected boolean isAdmin;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDate;
    @XmlElement(required = true)
    protected String updatedBy;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updatedDate;
    protected boolean userAgreementAccepted;
    protected boolean privacyPolicyAgreementAccepted;
    protected boolean onBoardingComplete;
    @XmlElement(required = true)
    protected String mobilePhone;
    @XmlElement(required = true)
    protected String officePhone;
    @XmlElement(required = true)
    protected String password;
    @XmlElement(required = true)
    protected String passcode;
    @XmlElement(required = true)
    protected String roles;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the profileImage property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getProfileImage() {
        return profileImage;
    }

    /**
     * Sets the value of the profileImage property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setProfileImage(byte[] value) {
        this.profileImage = value;
    }

    /**
     * Gets the value of the emailId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailId() {
        return emailId;
    }

    /**
     * Sets the value of the emailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailId(String value) {
        this.emailId = value;
    }

    /**
     * Gets the value of the isAdmin property.
     * 
     */
    public boolean isIsAdmin() {
        return isAdmin;
    }

    /**
     * Sets the value of the isAdmin property.
     * 
     */
    public void setIsAdmin(boolean value) {
        this.isAdmin = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedBy(String value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedDate(XMLGregorianCalendar value) {
        this.updatedDate = value;
    }

    /**
     * Gets the value of the userAgreementAccepted property.
     * 
     */
    public boolean isUserAgreementAccepted() {
        return userAgreementAccepted;
    }

    /**
     * Sets the value of the userAgreementAccepted property.
     * 
     */
    public void setUserAgreementAccepted(boolean value) {
        this.userAgreementAccepted = value;
    }

    /**
     * Gets the value of the privacyPolicyAgreementAccepted property.
     * 
     */
    public boolean isPrivacyPolicyAgreementAccepted() {
        return privacyPolicyAgreementAccepted;
    }

    /**
     * Sets the value of the privacyPolicyAgreementAccepted property.
     * 
     */
    public void setPrivacyPolicyAgreementAccepted(boolean value) {
        this.privacyPolicyAgreementAccepted = value;
    }

    /**
     * Gets the value of the onBoardingComplete property.
     * 
     */
    public boolean isOnBoardingComplete() {
        return onBoardingComplete;
    }

    /**
     * Sets the value of the onBoardingComplete property.
     * 
     */
    public void setOnBoardingComplete(boolean value) {
        this.onBoardingComplete = value;
    }

    /**
     * Gets the value of the mobilePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * Sets the value of the mobilePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilePhone(String value) {
        this.mobilePhone = value;
    }

    /**
     * Gets the value of the officePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficePhone() {
        return officePhone;
    }

    /**
     * Sets the value of the officePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficePhone(String value) {
        this.officePhone = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the passcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasscode() {
        return passcode;
    }

    /**
     * Sets the value of the passcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasscode(String value) {
        this.passcode = value;
    }

    /**
     * Gets the value of the roles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoles() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoles(String value) {
        this.roles = value;
    }

}
