//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.15 at 12:09:26 AM EDT 
//


package com.taksila.veda.model.api.course.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.taksila.veda.model.api.base.v1_0.BaseRequest;


/**
 * 
 * 				This represents the api structure of the CreateNewCourseRequest				
 * 			
 * 
 * <p>Java class for CreateNewCourseRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateNewCourseRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/api/base/v1_0}BaseRequest">
 *       &lt;sequence>
 *         &lt;element name="newCourse" type="{http://www.taksila.com/veda/model/api/course/v1_0}Course"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateNewCourseRequest", propOrder = {
    "newCourse"
})
public class CreateNewCourseRequest
    extends BaseRequest
{

    @XmlElement(required = true)
    protected Course newCourse;

    /**
     * Gets the value of the newCourse property.
     * 
     * @return
     *     possible object is
     *     {@link Course }
     *     
     */
    public Course getNewCourse() {
        return newCourse;
    }

    /**
     * Sets the value of the newCourse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Course }
     *     
     */
    public void setNewCourse(Course value) {
        this.newCourse = value;
    }

}
