//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.30 at 08:40:04 AM EDT 
//


package com.taksila.veda.model.api.course.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.taksila.veda.model.api.base.v1_0.BaseResponse;


/**
 * 
 * 				This represents the api structure of the CreateSlideResponse response 				
 * 			
 * 
 * <p>Java class for CreateSlideResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateSlideResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/api/base/v1_0}BaseResponse">
 *       &lt;sequence>
 *         &lt;element name="slide" type="{http://www.taksila.com/veda/model/api/course/v1_0}Slide"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateSlideResponse", propOrder = {
    "slide"
})
public class CreateSlideResponse
    extends BaseResponse
{

    @XmlElement(required = true)
    protected Slide slide;

    /**
     * Gets the value of the slide property.
     * 
     * @return
     *     possible object is
     *     {@link Slide }
     *     
     */
    public Slide getSlide() {
        return slide;
    }

    /**
     * Sets the value of the slide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Slide }
     *     
     */
    public void setSlide(Slide value) {
        this.slide = value;
    }

}
