//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 01:45:20 PM EST 
//


package com.taksila.veda.model.api.course.v1_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.taksila.veda.model.api.course.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.taksila.veda.model.api.course.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteCourseResponse }
     * 
     */
    public DeleteCourseResponse createDeleteCourseResponse() {
        return new DeleteCourseResponse();
    }

    /**
     * Create an instance of {@link Chapter }
     * 
     */
    public Chapter createChapter() {
        return new Chapter();
    }

    /**
     * Create an instance of {@link GetCourseInfoRequest }
     * 
     */
    public GetCourseInfoRequest createGetCourseInfoRequest() {
        return new GetCourseInfoRequest();
    }

    /**
     * Create an instance of {@link GetCourseInfoResponse }
     * 
     */
    public GetCourseInfoResponse createGetCourseInfoResponse() {
        return new GetCourseInfoResponse();
    }

    /**
     * Create an instance of {@link UpdateCourseRequest }
     * 
     */
    public UpdateCourseRequest createUpdateCourseRequest() {
        return new UpdateCourseRequest();
    }

    /**
     * Create an instance of {@link DeleteCourseRequest }
     * 
     */
    public DeleteCourseRequest createDeleteCourseRequest() {
        return new DeleteCourseRequest();
    }

    /**
     * Create an instance of {@link Slide }
     * 
     */
    public Slide createSlide() {
        return new Slide();
    }

    /**
     * Create an instance of {@link SearchCourseRequest }
     * 
     */
    public SearchCourseRequest createSearchCourseRequest() {
        return new SearchCourseRequest();
    }

    /**
     * Create an instance of {@link CreateNewCourseResponse }
     * 
     */
    public CreateNewCourseResponse createCreateNewCourseResponse() {
        return new CreateNewCourseResponse();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link CreateNewCourseRequest }
     * 
     */
    public CreateNewCourseRequest createCreateNewCourseRequest() {
        return new CreateNewCourseRequest();
    }

    /**
     * Create an instance of {@link UpdateCourseResponse }
     * 
     */
    public UpdateCourseResponse createUpdateCourseResponse() {
        return new UpdateCourseResponse();
    }

    /**
     * Create an instance of {@link Topic }
     * 
     */
    public Topic createTopic() {
        return new Topic();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link SearchCourseResponse }
     * 
     */
    public SearchCourseResponse createSearchCourseResponse() {
        return new SearchCourseResponse();
    }

}
