//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.17 at 05:55:12 PM EDT 
//


package com.taksila.veda.model.api.course.v1_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.taksila.veda.model.api.course.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.taksila.veda.model.api.course.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetChapterResponse }
     * 
     */
    public GetChapterResponse createGetChapterResponse() {
        return new GetChapterResponse();
    }

    /**
     * Create an instance of {@link UpdateSlideResponse }
     * 
     */
    public UpdateSlideResponse createUpdateSlideResponse() {
        return new UpdateSlideResponse();
    }

    /**
     * Create an instance of {@link GetTopicResponse }
     * 
     */
    public GetTopicResponse createGetTopicResponse() {
        return new GetTopicResponse();
    }

    /**
     * Create an instance of {@link DeleteCourseResponse }
     * 
     */
    public DeleteCourseResponse createDeleteCourseResponse() {
        return new DeleteCourseResponse();
    }

    /**
     * Create an instance of {@link UpdateChapterRequest }
     * 
     */
    public UpdateChapterRequest createUpdateChapterRequest() {
        return new UpdateChapterRequest();
    }

    /**
     * Create an instance of {@link DeleteChapterRequest }
     * 
     */
    public DeleteChapterRequest createDeleteChapterRequest() {
        return new DeleteChapterRequest();
    }

    /**
     * Create an instance of {@link GetTopicRequest }
     * 
     */
    public GetTopicRequest createGetTopicRequest() {
        return new GetTopicRequest();
    }

    /**
     * Create an instance of {@link SearchTopicsRequest }
     * 
     */
    public SearchTopicsRequest createSearchTopicsRequest() {
        return new SearchTopicsRequest();
    }

    /**
     * Create an instance of {@link GetCourseInfoRequest }
     * 
     */
    public GetCourseInfoRequest createGetCourseInfoRequest() {
        return new GetCourseInfoRequest();
    }

    /**
     * Create an instance of {@link UpdateTopicResponse }
     * 
     */
    public UpdateTopicResponse createUpdateTopicResponse() {
        return new UpdateTopicResponse();
    }

    /**
     * Create an instance of {@link UploadFileResponse }
     * 
     */
    public UploadFileResponse createUploadFileResponse() {
        return new UploadFileResponse();
    }

    /**
     * Create an instance of {@link GetCourseInfoResponse }
     * 
     */
    public GetCourseInfoResponse createGetCourseInfoResponse() {
        return new GetCourseInfoResponse();
    }

    /**
     * Create an instance of {@link SearchSlidesRequest }
     * 
     */
    public SearchSlidesRequest createSearchSlidesRequest() {
        return new SearchSlidesRequest();
    }

    /**
     * Create an instance of {@link SearchChaptersRequest }
     * 
     */
    public SearchChaptersRequest createSearchChaptersRequest() {
        return new SearchChaptersRequest();
    }

    /**
     * Create an instance of {@link UpdateCourseRequest }
     * 
     */
    public UpdateCourseRequest createUpdateCourseRequest() {
        return new UpdateCourseRequest();
    }

    /**
     * Create an instance of {@link DeleteSlideRequest }
     * 
     */
    public DeleteSlideRequest createDeleteSlideRequest() {
        return new DeleteSlideRequest();
    }

    /**
     * Create an instance of {@link Slide }
     * 
     */
    public Slide createSlide() {
        return new Slide();
    }

    /**
     * Create an instance of {@link GetChapterRequest }
     * 
     */
    public GetChapterRequest createGetChapterRequest() {
        return new GetChapterRequest();
    }

    /**
     * Create an instance of {@link CreateSlideResponse }
     * 
     */
    public CreateSlideResponse createCreateSlideResponse() {
        return new CreateSlideResponse();
    }

    /**
     * Create an instance of {@link CreateNewCourseRequest }
     * 
     */
    public CreateNewCourseRequest createCreateNewCourseRequest() {
        return new CreateNewCourseRequest();
    }

    /**
     * Create an instance of {@link SearchTopicsResponse }
     * 
     */
    public SearchTopicsResponse createSearchTopicsResponse() {
        return new SearchTopicsResponse();
    }

    /**
     * Create an instance of {@link DeleteTopicRequest }
     * 
     */
    public DeleteTopicRequest createDeleteTopicRequest() {
        return new DeleteTopicRequest();
    }

    /**
     * Create an instance of {@link CreateChapterResponse }
     * 
     */
    public CreateChapterResponse createCreateChapterResponse() {
        return new CreateChapterResponse();
    }

    /**
     * Create an instance of {@link DeleteChapterResponse }
     * 
     */
    public DeleteChapterResponse createDeleteChapterResponse() {
        return new DeleteChapterResponse();
    }

    /**
     * Create an instance of {@link CreateSlideRequest }
     * 
     */
    public CreateSlideRequest createCreateSlideRequest() {
        return new CreateSlideRequest();
    }

    /**
     * Create an instance of {@link Topic }
     * 
     */
    public Topic createTopic() {
        return new Topic();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link Chapter }
     * 
     */
    public Chapter createChapter() {
        return new Chapter();
    }

    /**
     * Create an instance of {@link DeleteTopicResponse }
     * 
     */
    public DeleteTopicResponse createDeleteTopicResponse() {
        return new DeleteTopicResponse();
    }

    /**
     * Create an instance of {@link DeleteSlideResponse }
     * 
     */
    public DeleteSlideResponse createDeleteSlideResponse() {
        return new DeleteSlideResponse();
    }

    /**
     * Create an instance of {@link CreateTopicRequest }
     * 
     */
    public CreateTopicRequest createCreateTopicRequest() {
        return new CreateTopicRequest();
    }

    /**
     * Create an instance of {@link CreateTopicResponse }
     * 
     */
    public CreateTopicResponse createCreateTopicResponse() {
        return new CreateTopicResponse();
    }

    /**
     * Create an instance of {@link GetSlideRequest }
     * 
     */
    public GetSlideRequest createGetSlideRequest() {
        return new GetSlideRequest();
    }

    /**
     * Create an instance of {@link UploadedFile }
     * 
     */
    public UploadedFile createUploadedFile() {
        return new UploadedFile();
    }

    /**
     * Create an instance of {@link DeleteCourseRequest }
     * 
     */
    public DeleteCourseRequest createDeleteCourseRequest() {
        return new DeleteCourseRequest();
    }

    /**
     * Create an instance of {@link SearchChaptersResponse }
     * 
     */
    public SearchChaptersResponse createSearchChaptersResponse() {
        return new SearchChaptersResponse();
    }

    /**
     * Create an instance of {@link SearchCourseRequest }
     * 
     */
    public SearchCourseRequest createSearchCourseRequest() {
        return new SearchCourseRequest();
    }

    /**
     * Create an instance of {@link CreateNewCourseResponse }
     * 
     */
    public CreateNewCourseResponse createCreateNewCourseResponse() {
        return new CreateNewCourseResponse();
    }

    /**
     * Create an instance of {@link CreateChapterRequest }
     * 
     */
    public CreateChapterRequest createCreateChapterRequest() {
        return new CreateChapterRequest();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link SearchSlidesResponse }
     * 
     */
    public SearchSlidesResponse createSearchSlidesResponse() {
        return new SearchSlidesResponse();
    }

    /**
     * Create an instance of {@link UpdateCourseResponse }
     * 
     */
    public UpdateCourseResponse createUpdateCourseResponse() {
        return new UpdateCourseResponse();
    }

    /**
     * Create an instance of {@link UpdateSlideRequest }
     * 
     */
    public UpdateSlideRequest createUpdateSlideRequest() {
        return new UpdateSlideRequest();
    }

    /**
     * Create an instance of {@link UpdateTopicRequest }
     * 
     */
    public UpdateTopicRequest createUpdateTopicRequest() {
        return new UpdateTopicRequest();
    }

    /**
     * Create an instance of {@link GetSlideResponse }
     * 
     */
    public GetSlideResponse createGetSlideResponse() {
        return new GetSlideResponse();
    }

    /**
     * Create an instance of {@link UpdateChapterResponse }
     * 
     */
    public UpdateChapterResponse createUpdateChapterResponse() {
        return new UpdateChapterResponse();
    }

    /**
     * Create an instance of {@link SearchCourseResponse }
     * 
     */
    public SearchCourseResponse createSearchCourseResponse() {
        return new SearchCourseResponse();
    }

}
