//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.17 at 05:55:12 PM EDT 
//


package com.taksila.veda.model.api.course.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.taksila.veda.model.api.base.v1_0.SearchRequest;


/**
 * 
 * 				This represents the api structure of the SearchSlidesRequest				
 * 			
 * 
 * <p>Java class for SearchSlidesRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchSlidesRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/api/base/v1_0}SearchRequest">
 *       &lt;sequence>
 *         &lt;element name="searchParam" type="{http://www.taksila.com/veda/model/api/course/v1_0}Slide"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchSlidesRequest", propOrder = {
    "searchParam"
})
public class SearchSlidesRequest
    extends SearchRequest
{

    @XmlElement(required = true)
    protected Slide searchParam;

    /**
     * Gets the value of the searchParam property.
     * 
     * @return
     *     possible object is
     *     {@link Slide }
     *     
     */
    public Slide getSearchParam() {
        return searchParam;
    }

    /**
     * Sets the value of the searchParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link Slide }
     *     
     */
    public void setSearchParam(Slide value) {
        this.searchParam = value;
    }

}
