//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 05:53:47 AM EDT 
//


package com.taksila.veda.model.api.classroom.v1_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.taksila.veda.model.api.classroom.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.taksila.veda.model.api.classroom.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateClassroomRequest }
     * 
     */
    public CreateClassroomRequest createCreateClassroomRequest() {
        return new CreateClassroomRequest();
    }

    /**
     * Create an instance of {@link SearchClassroomRequest }
     * 
     */
    public SearchClassroomRequest createSearchClassroomRequest() {
        return new SearchClassroomRequest();
    }

    /**
     * Create an instance of {@link UpdateClassroomResponse }
     * 
     */
    public UpdateClassroomResponse createUpdateClassroomResponse() {
        return new UpdateClassroomResponse();
    }

    /**
     * Create an instance of {@link DeleteClassroomRequest }
     * 
     */
    public DeleteClassroomRequest createDeleteClassroomRequest() {
        return new DeleteClassroomRequest();
    }

    /**
     * Create an instance of {@link Classroom }
     * 
     */
    public Classroom createClassroom() {
        return new Classroom();
    }

    /**
     * Create an instance of {@link GetClassroomResponse }
     * 
     */
    public GetClassroomResponse createGetClassroomResponse() {
        return new GetClassroomResponse();
    }

    /**
     * Create an instance of {@link GetClassroomRequest }
     * 
     */
    public GetClassroomRequest createGetClassroomRequest() {
        return new GetClassroomRequest();
    }

    /**
     * Create an instance of {@link UpdateClassroomRequest }
     * 
     */
    public UpdateClassroomRequest createUpdateClassroomRequest() {
        return new UpdateClassroomRequest();
    }

    /**
     * Create an instance of {@link SearchClassroomResponse }
     * 
     */
    public SearchClassroomResponse createSearchClassroomResponse() {
        return new SearchClassroomResponse();
    }

    /**
     * Create an instance of {@link DeleteClassroomResponse }
     * 
     */
    public DeleteClassroomResponse createDeleteClassroomResponse() {
        return new DeleteClassroomResponse();
    }

    /**
     * Create an instance of {@link CreateClassroomResponse }
     * 
     */
    public CreateClassroomResponse createCreateClassroomResponse() {
        return new CreateClassroomResponse();
    }

}
