//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.09 at 06:09:45 AM EDT 
//


package com.taksila.veda.model.api.config.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Flag complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Flag">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.taksila.com/veda/model/api/config/v1_0}flagId"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/api/config/v1_0}flagValue"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Flag", propOrder = {
    "flagId",
    "flagValue"
})
public class Flag {

    @XmlElement(required = true)
    protected String flagId;
    @XmlElement(required = true)
    protected String flagValue;

    /**
     * Gets the value of the flagId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagId() {
        return flagId;
    }

    /**
     * Sets the value of the flagId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagId(String value) {
        this.flagId = value;
    }

    /**
     * Gets the value of the flagValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagValue() {
        return flagValue;
    }

    /**
     * Sets the value of the flagValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagValue(String value) {
        this.flagValue = value;
    }

}
