//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.09 at 06:09:45 AM EDT 
//


package com.taksila.veda.model.api.config.v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.taksila.veda.model.db.base.v1_0.UserRole;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.taksila.veda.model.api.config.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FlagValue_QNAME = new QName("http://www.taksila.com/veda/model/api/config/v1_0", "flagValue");
    private final static QName _FlagId_QNAME = new QName("http://www.taksila.com/veda/model/api/config/v1_0", "flagId");
    private final static QName _ForRole_QNAME = new QName("http://www.taksila.com/veda/model/api/config/v1_0", "forRole");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.taksila.veda.model.api.config.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetApplicationFlagsResponse }
     * 
     */
    public GetApplicationFlagsResponse createGetApplicationFlagsResponse() {
        return new GetApplicationFlagsResponse();
    }

    /**
     * Create an instance of {@link GetApplicationFlagsRequest }
     * 
     */
    public GetApplicationFlagsRequest createGetApplicationFlagsRequest() {
        return new GetApplicationFlagsRequest();
    }

    /**
     * Create an instance of {@link UpdateConfigRequest }
     * 
     */
    public UpdateConfigRequest createUpdateConfigRequest() {
        return new UpdateConfigRequest();
    }

    /**
     * Create an instance of {@link GetConfigurationRequest }
     * 
     */
    public GetConfigurationRequest createGetConfigurationRequest() {
        return new GetConfigurationRequest();
    }

    /**
     * Create an instance of {@link GetConfigurationResponse }
     * 
     */
    public GetConfigurationResponse createGetConfigurationResponse() {
        return new GetConfigurationResponse();
    }

    /**
     * Create an instance of {@link Flag }
     * 
     */
    public Flag createFlag() {
        return new Flag();
    }

    /**
     * Create an instance of {@link UpdateConfigResponse }
     * 
     */
    public UpdateConfigResponse createUpdateConfigResponse() {
        return new UpdateConfigResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/api/config/v1_0", name = "flagValue")
    public JAXBElement<String> createFlagValue(String value) {
        return new JAXBElement<String>(_FlagValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/api/config/v1_0", name = "flagId")
    public JAXBElement<String> createFlagId(String value) {
        return new JAXBElement<String>(_FlagId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/api/config/v1_0", name = "forRole")
    public JAXBElement<UserRole> createForRole(UserRole value) {
        return new JAXBElement<UserRole>(_ForRole_QNAME, UserRole.class, null, value);
    }

}
