//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.09 at 06:09:45 AM EDT 
//


package com.taksila.veda.model.api.config.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.taksila.veda.model.api.base.v1_0.BaseRequest;
import com.taksila.veda.model.db.config.v1_0.Config;


/**
 * 
 * 				This represents the api structure of the UpdateConfigRequest				
 * 			
 * 
 * <p>Java class for UpdateConfigRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateConfigRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/api/base/v1_0}BaseRequest">
 *       &lt;sequence>
 *         &lt;element name="configs" type="{http://www.taksila.com/veda/model/db/config/v1_0}Config" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateConfigRequest", propOrder = {
    "configs"
})
public class UpdateConfigRequest
    extends BaseRequest
{

    @XmlElement(required = true)
    protected List<Config> configs;

    /**
     * Gets the value of the configs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the configs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfigs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Config }
     * 
     * 
     */
    public List<Config> getConfigs() {
        if (configs == null) {
            configs = new ArrayList<Config>();
        }
        return this.configs;
    }

}
