//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.30 at 08:40:04 AM EDT 
//


package com.taksila.veda.model.db.course.v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.taksila.veda.model.db.course.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Filename_QNAME = new QName("http://www.taksila.com/veda/model/db/course/v1_0", "filename");
    private final static QName _Name_QNAME = new QName("http://www.taksila.com/veda/model/db/course/v1_0", "name");
    private final static QName _FileType_QNAME = new QName("http://www.taksila.com/veda/model/db/course/v1_0", "fileType");
    private final static QName _ContentImageId_QNAME = new QName("http://www.taksila.com/veda/model/db/course/v1_0", "contentImageId");
    private final static QName _TextContent_QNAME = new QName("http://www.taksila.com/veda/model/db/course/v1_0", "textContent");
    private final static QName _FileProcessingCode_QNAME = new QName("http://www.taksila.com/veda/model/db/course/v1_0", "fileProcessingCode");
    private final static QName _Tags_QNAME = new QName("http://www.taksila.com/veda/model/db/course/v1_0", "tags");
    private final static QName _Topicid_QNAME = new QName("http://www.taksila.com/veda/model/db/course/v1_0", "topicid");
    private final static QName _SubTitle_QNAME = new QName("http://www.taksila.com/veda/model/db/course/v1_0", "subTitle");
    private final static QName _Id_QNAME = new QName("http://www.taksila.com/veda/model/db/course/v1_0", "id");
    private final static QName _Notes_QNAME = new QName("http://www.taksila.com/veda/model/db/course/v1_0", "notes");
    private final static QName _Description_QNAME = new QName("http://www.taksila.com/veda/model/db/course/v1_0", "description");
    private final static QName _Title_QNAME = new QName("http://www.taksila.com/veda/model/db/course/v1_0", "title");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.taksila.veda.model.db.course.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NoteTable }
     * 
     */
    public NoteTable createNoteTable() {
        return new NoteTable();
    }

    /**
     * Create an instance of {@link CourseTable }
     * 
     */
    public CourseTable createCourseTable() {
        return new CourseTable();
    }

    /**
     * Create an instance of {@link SlideTable }
     * 
     */
    public SlideTable createSlideTable() {
        return new SlideTable();
    }

    /**
     * Create an instance of {@link UploadedFileTable }
     * 
     */
    public UploadedFileTable createUploadedFileTable() {
        return new UploadedFileTable();
    }

    /**
     * Create an instance of {@link TopicTable }
     * 
     */
    public TopicTable createTopicTable() {
        return new TopicTable();
    }

    /**
     * Create an instance of {@link ChapterTable }
     * 
     */
    public ChapterTable createChapterTable() {
        return new ChapterTable();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/course/v1_0", name = "filename")
    public JAXBElement<String> createFilename(String value) {
        return new JAXBElement<String>(_Filename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/course/v1_0", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/course/v1_0", name = "fileType")
    public JAXBElement<String> createFileType(String value) {
        return new JAXBElement<String>(_FileType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/course/v1_0", name = "contentImageId")
    public JAXBElement<String> createContentImageId(String value) {
        return new JAXBElement<String>(_ContentImageId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/course/v1_0", name = "textContent")
    public JAXBElement<String> createTextContent(String value) {
        return new JAXBElement<String>(_TextContent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/course/v1_0", name = "fileProcessingCode")
    public JAXBElement<String> createFileProcessingCode(String value) {
        return new JAXBElement<String>(_FileProcessingCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/course/v1_0", name = "tags")
    public JAXBElement<String> createTags(String value) {
        return new JAXBElement<String>(_Tags_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/course/v1_0", name = "topicid")
    public JAXBElement<Integer> createTopicid(Integer value) {
        return new JAXBElement<Integer>(_Topicid_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/course/v1_0", name = "subTitle")
    public JAXBElement<String> createSubTitle(String value) {
        return new JAXBElement<String>(_SubTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/course/v1_0", name = "id")
    public JAXBElement<Integer> createId(Integer value) {
        return new JAXBElement<Integer>(_Id_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoteTable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/course/v1_0", name = "notes")
    public JAXBElement<NoteTable> createNotes(NoteTable value) {
        return new JAXBElement<NoteTable>(_Notes_QNAME, NoteTable.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/course/v1_0", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/course/v1_0", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

}
