//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.10 at 08:31:09 AM EDT 
//


package com.taksila.veda.model.db.base.v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.taksila.veda.model.db.base.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TenantName_QNAME = new QName("http://www.taksila.com/veda/model/db/base/v1_0", "tenantName");
    private final static QName _Id_QNAME = new QName("http://www.taksila.com/veda/model/db/base/v1_0", "id");
    private final static QName _TenantStatus_QNAME = new QName("http://www.taksila.com/veda/model/db/base/v1_0", "tenantStatus");
    private final static QName _TenantId_QNAME = new QName("http://www.taksila.com/veda/model/db/base/v1_0", "tenantId");
    private final static QName _LastUpdatedDateTime_QNAME = new QName("http://www.taksila.com/veda/model/db/base/v1_0", "lastUpdatedDateTime");
    private final static QName _AllowedRoles_QNAME = new QName("http://www.taksila.com/veda/model/db/base/v1_0", "allowedRoles");
    private final static QName _UpdatedBy_QNAME = new QName("http://www.taksila.com/veda/model/db/base/v1_0", "updatedBy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.taksila.veda.model.db.base.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link BaseTable }
     * 
     */
    public BaseTable createBaseTable() {
        return new BaseTable();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/base/v1_0", name = "tenantName")
    public JAXBElement<String> createTenantName(String value) {
        return new JAXBElement<String>(_TenantName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/base/v1_0", name = "id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/base/v1_0", name = "tenantStatus")
    public JAXBElement<String> createTenantStatus(String value) {
        return new JAXBElement<String>(_TenantStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/base/v1_0", name = "tenantId")
    public JAXBElement<String> createTenantId(String value) {
        return new JAXBElement<String>(_TenantId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/base/v1_0", name = "lastUpdatedDateTime")
    public JAXBElement<XMLGregorianCalendar> createLastUpdatedDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_LastUpdatedDateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/base/v1_0", name = "allowedRoles")
    public JAXBElement<UserRole> createAllowedRoles(UserRole value) {
        return new JAXBElement<UserRole>(_AllowedRoles_QNAME, UserRole.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/base/v1_0", name = "updatedBy")
    public JAXBElement<String> createUpdatedBy(String value) {
        return new JAXBElement<String>(_UpdatedBy_QNAME, String.class, null, value);
    }

}
