//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.21 at 07:43:54 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.taksila.com/veda/model/db/base/v1_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.taksila.veda.model.db.base.v1_0;
