//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 07:36:10 PM EST 
//


package com.taksila.veda.model.api.security.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.taksila.veda.model.api.base.v1_0.BaseResponse;


/**
 * 
 * 				This represents the api structure of the GenerateVerificationTokenResponse response 				
 * 			
 * 
 * <p>Java class for GenerateVerificationTokenResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenerateVerificationTokenResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/api/base/v1_0}BaseResponse">
 *       &lt;sequence>
 *         &lt;element name="passwordResetVerificationToken" type="{http://www.taksila.com/veda/model/api/security/v1_0}PasswordResetVerificationToken"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenerateVerificationTokenResponse", propOrder = {
    "passwordResetVerificationToken"
})
public class GenerateVerificationTokenResponse
    extends BaseResponse
{

    @XmlElement(required = true)
    protected PasswordResetVerificationToken passwordResetVerificationToken;

    /**
     * Gets the value of the passwordResetVerificationToken property.
     * 
     * @return
     *     possible object is
     *     {@link PasswordResetVerificationToken }
     *     
     */
    public PasswordResetVerificationToken getPasswordResetVerificationToken() {
        return passwordResetVerificationToken;
    }

    /**
     * Sets the value of the passwordResetVerificationToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link PasswordResetVerificationToken }
     *     
     */
    public void setPasswordResetVerificationToken(PasswordResetVerificationToken value) {
        this.passwordResetVerificationToken = value;
    }

}
