//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 03:53:26 PM EST 
//


package com.taksila.veda.model.api.security.v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.taksila.veda.model.api.security.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Success_QNAME = new QName("http://www.taksila.com/veda/model/api/security/v1_0", "success");
    private final static QName _Status_QNAME = new QName("http://www.taksila.com/veda/model/api/security/v1_0", "status");
    private final static QName _NewPasswordConfirm_QNAME = new QName("http://www.taksila.com/veda/model/api/security/v1_0", "newPasswordConfirm");
    private final static QName _NewPassword_QNAME = new QName("http://www.taksila.com/veda/model/api/security/v1_0", "newPassword");
    private final static QName _Msg_QNAME = new QName("http://www.taksila.com/veda/model/api/security/v1_0", "msg");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.taksila.veda.model.api.security.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResetPasswordRequest }
     * 
     */
    public ResetPasswordRequest createResetPasswordRequest() {
        return new ResetPasswordRequest();
    }

    /**
     * Create an instance of {@link ResetPasswordResponse }
     * 
     */
    public ResetPasswordResponse createResetPasswordResponse() {
        return new ResetPasswordResponse();
    }

    /**
     * Create an instance of {@link GenerateVerificationTokenResponse }
     * 
     */
    public GenerateVerificationTokenResponse createGenerateVerificationTokenResponse() {
        return new GenerateVerificationTokenResponse();
    }

    /**
     * Create an instance of {@link EmailPasswordResetResponse }
     * 
     */
    public EmailPasswordResetResponse createEmailPasswordResetResponse() {
        return new EmailPasswordResetResponse();
    }

    /**
     * Create an instance of {@link PasswordResetVerificationToken }
     * 
     */
    public PasswordResetVerificationToken createPasswordResetVerificationToken() {
        return new PasswordResetVerificationToken();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/api/security/v1_0", name = "success")
    public JAXBElement<Boolean> createSuccess(Boolean value) {
        return new JAXBElement<Boolean>(_Success_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/api/security/v1_0", name = "status")
    public JAXBElement<StatusType> createStatus(StatusType value) {
        return new JAXBElement<StatusType>(_Status_QNAME, StatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/api/security/v1_0", name = "newPasswordConfirm")
    public JAXBElement<String> createNewPasswordConfirm(String value) {
        return new JAXBElement<String>(_NewPasswordConfirm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/api/security/v1_0", name = "newPassword")
    public JAXBElement<String> createNewPassword(String value) {
        return new JAXBElement<String>(_NewPassword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/api/security/v1_0", name = "msg")
    public JAXBElement<String> createMsg(String value) {
        return new JAXBElement<String>(_Msg_QNAME, String.class, null, value);
    }

}
