//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 06:19:21 AM EDT 
//


package com.taksila.veda.model.api.security.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.taksila.veda.model.api.base.v1_0.BaseResponse;
import com.taksila.veda.model.db.security.v1_0.UserSession;
import com.taksila.veda.model.db.usermgmt.v1_0.User;


/**
 * 
 * 				This represents the api structure of the UserLoginResponse response 				
 * 			
 * 
 * <p>Java class for UserLoginResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserLoginResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/api/base/v1_0}BaseResponse">
 *       &lt;sequence>
 *         &lt;element name="userInfo" type="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}User"/>
 *         &lt;element name="sessionInfo" type="{http://www.taksila.com/veda/model/db/security/v1_0}UserSession"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserLoginResponse", propOrder = {
    "userInfo",
    "sessionInfo"
})
public class UserLoginResponse
    extends BaseResponse
{

    @XmlElement(required = true)
    protected User userInfo;
    @XmlElement(required = true)
    protected UserSession sessionInfo;

    /**
     * Gets the value of the userInfo property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUserInfo() {
        return userInfo;
    }

    /**
     * Sets the value of the userInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUserInfo(User value) {
        this.userInfo = value;
    }

    /**
     * Gets the value of the sessionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link UserSession }
     *     
     */
    public UserSession getSessionInfo() {
        return sessionInfo;
    }

    /**
     * Sets the value of the sessionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserSession }
     *     
     */
    public void setSessionInfo(UserSession value) {
        this.sessionInfo = value;
    }

}
