//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 05:53:47 AM EDT 
//


package com.taksila.veda.model.db.classroom.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.taksila.veda.model.db.base.v1_0.BaseTable;
import com.taksila.veda.model.db.usermgmt.v1_0.User;


/**
 * 
 * 				Classroom table has list of classrooms and its contents								
 * 			
 * 
 * <p>Java class for Classroom complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Classroom">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/db/base/v1_0}BaseTable">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/classroom/v1_0}name"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/classroom/v1_0}title"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/classroom/v1_0}subTitle"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/classroom/v1_0}description"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/classroom/v1_0}courseid"/>
 *         &lt;element name="enrolledStudents" type="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}User" maxOccurs="unbounded"/>
 *         &lt;element name="teacher" type="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}User"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Classroom", propOrder = {
    "name",
    "title",
    "subTitle",
    "description",
    "courseid",
    "enrolledStudents",
    "teacher"
})
@XmlSeeAlso({
    com.taksila.veda.model.api.classroom.v1_0.Classroom.class
})
public class Classroom
    extends BaseTable
{

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String subTitle;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String courseid;
    @XmlElement(required = true)
    protected List<User> enrolledStudents;
    @XmlElement(required = true)
    protected User teacher;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the subTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * Sets the value of the subTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubTitle(String value) {
        this.subTitle = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the courseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseid() {
        return courseid;
    }

    /**
     * Sets the value of the courseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseid(String value) {
        this.courseid = value;
    }

    /**
     * Gets the value of the enrolledStudents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enrolledStudents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnrolledStudents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link User }
     * 
     * 
     */
    public List<User> getEnrolledStudents() {
        if (enrolledStudents == null) {
            enrolledStudents = new ArrayList<User>();
        }
        return this.enrolledStudents;
    }

    /**
     * Gets the value of the teacher property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getTeacher() {
        return teacher;
    }

    /**
     * Sets the value of the teacher property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setTeacher(User value) {
        this.teacher = value;
    }

}
