//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.21 at 07:43:54 AM EDT 
//


package com.taksila.veda.model.db.classroom.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.taksila.veda.model.db.base.v1_0.BaseTable;


/**
 * 
 * 				Classroom table has list of classrooms and its contents								
 * 			
 * 
 * <p>Java class for Enrollment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Enrollment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/db/base/v1_0}BaseTable">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/classroom/v1_0}classroomid"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/classroom/v1_0}userRecordId"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/classroom/v1_0}enrolledOn"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/classroom/v1_0}verifiedBy"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/classroom/v1_0}enrollStatus"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/classroom/v1_0}startDate"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/classroom/v1_0}endDate"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Enrollment", propOrder = {
    "classroomid",
    "userRecordId",
    "enrolledOn",
    "verifiedBy",
    "enrollStatus",
    "startDate",
    "endDate"
})
@XmlSeeAlso({
    com.taksila.veda.model.api.classroom.v1_0.Enrollment.class
})
public class Enrollment
    extends BaseTable
{

    @XmlElement(required = true)
    protected String classroomid;
    @XmlElement(required = true)
    protected String userRecordId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar enrolledOn;
    @XmlElement(required = true)
    protected String verifiedBy;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected EnrollmentStatusType enrollStatus;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;

    /**
     * Gets the value of the classroomid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassroomid() {
        return classroomid;
    }

    /**
     * Sets the value of the classroomid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassroomid(String value) {
        this.classroomid = value;
    }

    /**
     * Gets the value of the userRecordId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserRecordId() {
        return userRecordId;
    }

    /**
     * Sets the value of the userRecordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserRecordId(String value) {
        this.userRecordId = value;
    }

    /**
     * Gets the value of the enrolledOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEnrolledOn() {
        return enrolledOn;
    }

    /**
     * Sets the value of the enrolledOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEnrolledOn(XMLGregorianCalendar value) {
        this.enrolledOn = value;
    }

    /**
     * Gets the value of the verifiedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerifiedBy() {
        return verifiedBy;
    }

    /**
     * Sets the value of the verifiedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerifiedBy(String value) {
        this.verifiedBy = value;
    }

    /**
     * Gets the value of the enrollStatus property.
     * 
     * @return
     *     possible object is
     *     {@link EnrollmentStatusType }
     *     
     */
    public EnrollmentStatusType getEnrollStatus() {
        return enrollStatus;
    }

    /**
     * Sets the value of the enrollStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnrollmentStatusType }
     *     
     */
    public void setEnrollStatus(EnrollmentStatusType value) {
        this.enrollStatus = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

}
