//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 05:53:47 AM EDT 
//


package com.taksila.veda.model.db.classroom.v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.taksila.veda.model.db.classroom.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Courseid_QNAME = new QName("http://www.taksila.com/veda/model/db/classroom/v1_0", "courseid");
    private final static QName _Title_QNAME = new QName("http://www.taksila.com/veda/model/db/classroom/v1_0", "title");
    private final static QName _Description_QNAME = new QName("http://www.taksila.com/veda/model/db/classroom/v1_0", "description");
    private final static QName _Name_QNAME = new QName("http://www.taksila.com/veda/model/db/classroom/v1_0", "name");
    private final static QName _SubTitle_QNAME = new QName("http://www.taksila.com/veda/model/db/classroom/v1_0", "subTitle");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.taksila.veda.model.db.classroom.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Classroom }
     * 
     */
    public Classroom createClassroom() {
        return new Classroom();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/classroom/v1_0", name = "courseid")
    public JAXBElement<String> createCourseid(String value) {
        return new JAXBElement<String>(_Courseid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/classroom/v1_0", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/classroom/v1_0", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/classroom/v1_0", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.taksila.com/veda/model/db/classroom/v1_0", name = "subTitle")
    public JAXBElement<String> createSubTitle(String value) {
        return new JAXBElement<String>(_SubTitle_QNAME, String.class, null, value);
    }

}
