//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.30 at 09:56:48 AM EST 
//


package com.taksila.veda.model.api.base.v1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecordType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RecordType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="USER"/>
 *     &lt;enumeration value="CLASSROOM"/>
 *     &lt;enumeration value="SLIDES"/>
 *     &lt;enumeration value="EVENTSCHEDULE"/>
 *     &lt;enumeration value="CONFIG"/>
 *     &lt;enumeration value="COURSE"/>
 *     &lt;enumeration value="ENROLLMENT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RecordType")
@XmlEnum
public enum RecordType {

    USER,
    CLASSROOM,
    SLIDES,
    EVENTSCHEDULE,
    CONFIG,
    COURSE,
    ENROLLMENT;

    public String value() {
        return name();
    }

    public static RecordType fromValue(String v) {
        return valueOf(v);
    }

}
