//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.09 at 08:22:33 AM EDT 
//


package com.taksila.veda.model.db.event_schedule_mgmt.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.taksila.veda.model.db.base.v1_0.BaseTable;


/**
 * 
 * 				Event schedule						
 * 			
 * 
 * <p>Java class for EventSchedule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventSchedule">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/db/base/v1_0}BaseTable">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0}eventRecordId"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0}eventStartDate"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0}eventEndDate"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0}eventType"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0}eventStatus"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0}eventTitle"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0}eventDescription"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventSchedule", propOrder = {
    "eventRecordId",
    "eventStartDate",
    "eventEndDate",
    "eventType",
    "eventStatus",
    "eventTitle",
    "eventDescription"
})
public class EventSchedule
    extends BaseTable
{

    @XmlElement(required = true)
    protected String eventRecordId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventStartDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventEndDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected EventType eventType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected EventStatusType eventStatus;
    @XmlElement(required = true)
    protected String eventTitle;
    @XmlElement(required = true)
    protected String eventDescription;

    /**
     * Gets the value of the eventRecordId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventRecordId() {
        return eventRecordId;
    }

    /**
     * Sets the value of the eventRecordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventRecordId(String value) {
        this.eventRecordId = value;
    }

    /**
     * Gets the value of the eventStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventStartDate() {
        return eventStartDate;
    }

    /**
     * Sets the value of the eventStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventStartDate(XMLGregorianCalendar value) {
        this.eventStartDate = value;
    }

    /**
     * Gets the value of the eventEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventEndDate() {
        return eventEndDate;
    }

    /**
     * Sets the value of the eventEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventEndDate(XMLGregorianCalendar value) {
        this.eventEndDate = value;
    }

    /**
     * Gets the value of the eventType property.
     * 
     * @return
     *     possible object is
     *     {@link EventType }
     *     
     */
    public EventType getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventType }
     *     
     */
    public void setEventType(EventType value) {
        this.eventType = value;
    }

    /**
     * Gets the value of the eventStatus property.
     * 
     * @return
     *     possible object is
     *     {@link EventStatusType }
     *     
     */
    public EventStatusType getEventStatus() {
        return eventStatus;
    }

    /**
     * Sets the value of the eventStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventStatusType }
     *     
     */
    public void setEventStatus(EventStatusType value) {
        this.eventStatus = value;
    }

    /**
     * Gets the value of the eventTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventTitle() {
        return eventTitle;
    }

    /**
     * Sets the value of the eventTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventTitle(String value) {
        this.eventTitle = value;
    }

    /**
     * Gets the value of the eventDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventDescription() {
        return eventDescription;
    }

    /**
     * Sets the value of the eventDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventDescription(String value) {
        this.eventDescription = value;
    }

}
