//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.18 at 06:25:47 PM EST 
//


package com.taksila.veda.model.db.event_schedule_mgmt.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.taksila.veda.model.db.base.v1_0.BaseTable;


/**
 * 
 * 				EventAttendance table has list of students who attended the session							
 * 			
 * 
 * <p>Java class for EventAttendance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventAttendance">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/db/base/v1_0}BaseTable">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0}eventScheduleId"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0}userRecordId"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0}startDate"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0}endDate"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventAttendance", propOrder = {
    "eventScheduleId",
    "userRecordId",
    "startDate",
    "endDate"
})
public class EventAttendance
    extends BaseTable
{

    @XmlElement(required = true)
    protected String eventScheduleId;
    @XmlElement(required = true)
    protected String userRecordId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;

    /**
     * Gets the value of the eventScheduleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventScheduleId() {
        return eventScheduleId;
    }

    /**
     * Sets the value of the eventScheduleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventScheduleId(String value) {
        this.eventScheduleId = value;
    }

    /**
     * Gets the value of the userRecordId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserRecordId() {
        return userRecordId;
    }

    /**
     * Sets the value of the userRecordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserRecordId(String value) {
        this.userRecordId = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

}
