//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.03 at 10:48:05 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.taksila.veda.model.db.event_schedule_mgmt.v1_0;
