//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.16 at 11:52:48 AM EDT 
//


package com.taksila.veda.model.db.usermgmt.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.taksila.veda.model.db.base.v1_0.BaseTable;


/**
 * 
 * 				UserInfo table to store the complete user information						
 * 			
 * 
 * <p>Java class for UserImageInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserImageInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/db/base/v1_0}BaseTable">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}userId"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}imageid"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}userImageType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserImageInfo", propOrder = {
    "userId",
    "imageid",
    "userImageType"
})
public class UserImageInfo
    extends BaseTable
{

    @XmlElement(required = true)
    protected String userId;
    @XmlElement(required = true)
    protected String imageid;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected UserImageType userImageType;

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the imageid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageid() {
        return imageid;
    }

    /**
     * Sets the value of the imageid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageid(String value) {
        this.imageid = value;
    }

    /**
     * Gets the value of the userImageType property.
     * 
     * @return
     *     possible object is
     *     {@link UserImageType }
     *     
     */
    public UserImageType getUserImageType() {
        return userImageType;
    }

    /**
     * Sets the value of the userImageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserImageType }
     *     
     */
    public void setUserImageType(UserImageType value) {
        this.userImageType = value;
    }

}
