//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.21 at 09:20:22 PM EDT 
//


package com.taksila.veda.model.db.usermgmt.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.taksila.veda.model.db.base.v1_0.BaseTable;
import com.taksila.veda.model.db.base.v1_0.UserRole;


/**
 * 
 * 				UserInfo table to store the complete user information						
 * 			
 * 
 * <p>Java class for User complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="User">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/db/base/v1_0}BaseTable">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}userId"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}emailId"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}firstName"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}middleName"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}lastName"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}userPswd"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}cellphone"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}okToText"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}officephone"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}officephoneExt"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}landlinephone"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}addressLine1"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}addressLine2"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}city"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}state"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}country"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}postalcode"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}userrole"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}changePswd"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}accountDeleted"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}accountDisabled"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/usermgmt/v1_0}lastLoginIp"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "User", propOrder = {
    "userId",
    "emailId",
    "firstName",
    "middleName",
    "lastName",
    "userPswd",
    "cellphone",
    "okToText",
    "officephone",
    "officephoneExt",
    "landlinephone",
    "addressLine1",
    "addressLine2",
    "city",
    "state",
    "country",
    "postalcode",
    "userrole",
    "changePswd",
    "accountDeleted",
    "accountDisabled",
    "lastLoginIp"
})
public class User
    extends BaseTable
{

    @XmlElement(required = true)
    protected String userId;
    @XmlElement(required = true)
    protected String emailId;
    @XmlElement(required = true)
    protected String firstName;
    @XmlElement(required = true)
    protected String middleName;
    @XmlElement(required = true)
    protected String lastName;
    @XmlElement(required = true)
    protected String userPswd;
    @XmlElement(required = true)
    protected String cellphone;
    protected boolean okToText;
    @XmlElement(required = true)
    protected String officephone;
    @XmlElement(required = true)
    protected String officephoneExt;
    @XmlElement(required = true)
    protected String landlinephone;
    @XmlElement(required = true)
    protected String addressLine1;
    @XmlElement(required = true)
    protected String addressLine2;
    @XmlElement(required = true)
    protected String city;
    @XmlElement(required = true)
    protected String state;
    @XmlElement(required = true)
    protected String country;
    @XmlElement(required = true)
    protected String postalcode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected UserRole userrole;
    protected boolean changePswd;
    protected boolean accountDeleted;
    protected boolean accountDisabled;
    @XmlElement(required = true)
    protected String lastLoginIp;

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the emailId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailId() {
        return emailId;
    }

    /**
     * Sets the value of the emailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailId(String value) {
        this.emailId = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the userPswd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserPswd() {
        return userPswd;
    }

    /**
     * Sets the value of the userPswd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserPswd(String value) {
        this.userPswd = value;
    }

    /**
     * Gets the value of the cellphone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * Sets the value of the cellphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellphone(String value) {
        this.cellphone = value;
    }

    /**
     * Gets the value of the okToText property.
     * 
     */
    public boolean isOkToText() {
        return okToText;
    }

    /**
     * Sets the value of the okToText property.
     * 
     */
    public void setOkToText(boolean value) {
        this.okToText = value;
    }

    /**
     * Gets the value of the officephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficephone() {
        return officephone;
    }

    /**
     * Sets the value of the officephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficephone(String value) {
        this.officephone = value;
    }

    /**
     * Gets the value of the officephoneExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficephoneExt() {
        return officephoneExt;
    }

    /**
     * Sets the value of the officephoneExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficephoneExt(String value) {
        this.officephoneExt = value;
    }

    /**
     * Gets the value of the landlinephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLandlinephone() {
        return landlinephone;
    }

    /**
     * Sets the value of the landlinephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLandlinephone(String value) {
        this.landlinephone = value;
    }

    /**
     * Gets the value of the addressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * Sets the value of the addressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine1(String value) {
        this.addressLine1 = value;
    }

    /**
     * Gets the value of the addressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * Sets the value of the addressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine2(String value) {
        this.addressLine2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the postalcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * Sets the value of the postalcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalcode(String value) {
        this.postalcode = value;
    }

    /**
     * Gets the value of the userrole property.
     * 
     * @return
     *     possible object is
     *     {@link UserRole }
     *     
     */
    public UserRole getUserrole() {
        return userrole;
    }

    /**
     * Sets the value of the userrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserRole }
     *     
     */
    public void setUserrole(UserRole value) {
        this.userrole = value;
    }

    /**
     * Gets the value of the changePswd property.
     * 
     */
    public boolean isChangePswd() {
        return changePswd;
    }

    /**
     * Sets the value of the changePswd property.
     * 
     */
    public void setChangePswd(boolean value) {
        this.changePswd = value;
    }

    /**
     * Gets the value of the accountDeleted property.
     * 
     */
    public boolean isAccountDeleted() {
        return accountDeleted;
    }

    /**
     * Sets the value of the accountDeleted property.
     * 
     */
    public void setAccountDeleted(boolean value) {
        this.accountDeleted = value;
    }

    /**
     * Gets the value of the accountDisabled property.
     * 
     */
    public boolean isAccountDisabled() {
        return accountDisabled;
    }

    /**
     * Sets the value of the accountDisabled property.
     * 
     */
    public void setAccountDisabled(boolean value) {
        this.accountDisabled = value;
    }

    /**
     * Gets the value of the lastLoginIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * Sets the value of the lastLoginIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastLoginIp(String value) {
        this.lastLoginIp = value;
    }

}
