//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.03 at 10:48:05 PM EDT 
//


package com.taksila.veda.model.api.event_schedule_mgmt.v1_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.taksila.veda.model.api.event_schedule_mgmt.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.taksila.veda.model.api.event_schedule_mgmt.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateEventScheduleResponse }
     * 
     */
    public UpdateEventScheduleResponse createUpdateEventScheduleResponse() {
        return new UpdateEventScheduleResponse();
    }

    /**
     * Create an instance of {@link SearchEventScheduleRequest }
     * 
     */
    public SearchEventScheduleRequest createSearchEventScheduleRequest() {
        return new SearchEventScheduleRequest();
    }

    /**
     * Create an instance of {@link DeleteEventScheduleRequest }
     * 
     */
    public DeleteEventScheduleRequest createDeleteEventScheduleRequest() {
        return new DeleteEventScheduleRequest();
    }

    /**
     * Create an instance of {@link GetEventScheduleRequest }
     * 
     */
    public GetEventScheduleRequest createGetEventScheduleRequest() {
        return new GetEventScheduleRequest();
    }

    /**
     * Create an instance of {@link SearchEventScheduleResponse }
     * 
     */
    public SearchEventScheduleResponse createSearchEventScheduleResponse() {
        return new SearchEventScheduleResponse();
    }

    /**
     * Create an instance of {@link UpdateEventScheduleRequest }
     * 
     */
    public UpdateEventScheduleRequest createUpdateEventScheduleRequest() {
        return new UpdateEventScheduleRequest();
    }

    /**
     * Create an instance of {@link DeleteEventScheduleResponse }
     * 
     */
    public DeleteEventScheduleResponse createDeleteEventScheduleResponse() {
        return new DeleteEventScheduleResponse();
    }

    /**
     * Create an instance of {@link CreateEventScheduleResponse }
     * 
     */
    public CreateEventScheduleResponse createCreateEventScheduleResponse() {
        return new CreateEventScheduleResponse();
    }

    /**
     * Create an instance of {@link GetEventScheduleResponse }
     * 
     */
    public GetEventScheduleResponse createGetEventScheduleResponse() {
        return new GetEventScheduleResponse();
    }

    /**
     * Create an instance of {@link CreateEventScheduleRequest }
     * 
     */
    public CreateEventScheduleRequest createCreateEventScheduleRequest() {
        return new CreateEventScheduleRequest();
    }

}
