//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.18 at 06:25:47 PM EST 
//


package com.taksila.veda.model.api.event_schedule_mgmt.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import com.taksila.veda.model.api.base.v1_0.SearchRequest;


/**
 * 
 * 				This represents the api structure of the SearchEventAttendanceRequest				
 * 			
 * 
 * <p>Java class for SearchEventAttendanceRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchEventAttendanceRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.taksila.com/veda/model/api/base/v1_0}SearchRequest">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0}eventAttendanceId"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/db/classroom/v1_0}classroomid"/>
 *         &lt;element ref="{http://www.taksila.com/veda/model/api/base/v1_0}userRecordId"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchEventAttendanceRequest", propOrder = {
    "rest"
})
public class SearchEventAttendanceRequest
    extends SearchRequest
{

    @XmlElementRefs({
        @XmlElementRef(name = "eventAttendanceId", namespace = "http://www.taksila.com/veda/model/db/event_schedule_mgmt/v1_0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "classroomid", namespace = "http://www.taksila.com/veda/model/db/classroom/v1_0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "userRecordId", namespace = "http://www.taksila.com/veda/model/api/base/v1_0", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<String>> rest;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "UserRecordId" is used by two different parts of a schema. See: 
     * line 212 of file:/C:/Users/Nxxxx/git/taksila/src/main/resources/xsd/veda_event_schedule_mgmt_api_model_v1_0.xsd
     * line 47 of file:/C:/Users/Nxxxx/git/taksila/src/main/resources/xsd/veda_base_model_v1.0.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getRest() {
        if (rest == null) {
            rest = new ArrayList<JAXBElement<String>>();
        }
        return this.rest;
    }

}
